# Generated by Django 3.2.7 on 2021-09-28 02:30

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='sueldo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
